name: me2_pack_loader
description: "Flutter desktop GUI for managing ModEngine2 mod packs."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  toml: ^0.18.0
  file_picker: ^8.1.7
  shared_preferences: ^2.3.5
  path: ^1.9.1
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  image: ^4.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
